# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# WARNING: AUTO-GENERATED FILE - DO NOT EDIT DIRECTLY
# 
# This file is automatically generated from infrastructure/config/api_routes.py
# by the sync_api_routes.py script.
# 
# To make changes, edit the source file and run sync_api_routes.py.
# Last synchronized: 2025-06-10 08:36:14
# 
# NOTE: This file was manually edited on 2025-06-11 to:
# 1. Remove the query_by_attribute route (GET content/query/{attribute}/{value})
#    as this functionality has been deprecated.
# 2. Remove list_content_by_publisher and list_content_by_publisher_and_type routes
#    as these have been consolidated into the search_content route.
# 3. Convert all GET routes to POST routes to prevent exposing parameters
#    in URLs and to ensure proper parameter type handling.
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

"""
API Gateway route configuration for Knowlio REST API.
Defines all processor actions as REST API endpoints with their HTTP methods and paths.
"""

from typing import List, Dict, Optional
from dataclasses import dataclass


@dataclass
class ApiRoute:
    """Configuration for a single API route"""
    method: str
    path: str
    processor_name: str
    action: str
    description: str
    path_parameters: Optional[List[str]] = None
    query_parameters: Optional[List[str]] = None
    auth_required: bool = False  # Whether the route requires Cognito authentication
    allowed_groups: Optional[List[str]] = None  # List of Cognito groups allowed to access this route


class KnowlioApiRoutes:
    """Central configuration for all Knowlio API routes"""
    
    @staticmethod
    def get_all_routes() -> List[ApiRoute]:
        """Return all API routes for the Knowlio system"""
        return [
            # User Management Routes
            ApiRoute(
                method="POST",
                path="register",
                processor_name="user",
                action="register_user",
                description="Register a new user",
            ),
            ApiRoute(
                method="POST",
                path="users/profile",
                processor_name="user",
                action="get_user_profile",
                description="Get user profile by ID (POST)",
                auth_required=True,
                allowed_groups=["Admin", "Publisher", "Consumer"]
            ),
            ApiRoute(
                method="PUT",
                path="users/profile/update",
                processor_name="user",
                action="update_user_profile",
                description="Update user profile",
                auth_required=True,
                allowed_groups=["Admin", "Publisher", "Consumer"]
            ),
            ApiRoute(
                method="POST",
                path="admin/users/search",
                processor_name="user",
                action="search_users",
                description="Search users with flexible criteria",
                auth_required=True,
                allowed_groups=["Admin"]
            ),
            ApiRoute(
                method="PATCH",
                path="admin/users/update/{user_id}",
                processor_name="user",
                action="admin_update_user",
                description="Admin-only generic field update",
                path_parameters=["user_id"],
                auth_required=True,
                allowed_groups=["Admin"]
            ),
            ApiRoute(
                method="POST",
                path="users/ai-consents",
                processor_name="user",
                action="update_ai_consents",
                description="Update AI consent preferences (training, reference, marketplace)",
                auth_required=True,
                allowed_groups=["Admin", "Publisher", "Consumer"]
            ),
            ApiRoute(
                method="POST",
                path="users/user-agreement",
                processor_name="user",
                action="update_user_agreement",
                description="Sign user agreement with version tracking",
                auth_required=True,
                allowed_groups=["Admin", "Publisher", "Consumer"]
            ),
            ApiRoute(
                method="POST",
                path="users/ai-consent-attributes",
                processor_name="user",
                action="get_ai_consent_attributes",
                description="Get all AI consent attributes (training, reference, marketplace)",
                auth_required=True,
                allowed_groups=["Admin", "Publisher", "Consumer"]
            ),
            ApiRoute(
                method="POST",
                path="users/agreement-attributes",
                processor_name="user",
                action="get_user_agreement_attributes",
                description="Get user agreement attributes only",
                auth_required=True,
                allowed_groups=["Admin", "Publisher", "Consumer"]
            ),
            
            # Content Management Routes - Restructured to avoid path parameter conflicts
            ApiRoute(
                method="POST",
                path="content/metadata/upload",
                processor_name="content",
                action="upload_content_metadata",
                description="Upload content metadata",
                auth_required=True,
                allowed_groups=["Admin", "Publisher"]
            ),
            ApiRoute(
                method="POST",
                path="content/get/{content_id}",
                processor_name="content",
                action="get_content_details",
                description="Get content details by ID (POST)",
                path_parameters=["content_id"],
                auth_required=True,
                allowed_groups=["Admin", "Publisher"]
            ),
            ApiRoute(
                method="PUT",
                path="content/update/{content_id}",
                processor_name="content",
                action="update_content_metadata",
                description="Update content metadata",
                path_parameters=["content_id"],
                auth_required=True,
                allowed_groups=["Admin", "Publisher"]
            ),
            ApiRoute(
                method="PATCH",
                path="content/attribute/{content_id}/{attribute}",
                processor_name="content",
                action="update_content_attribute",
                description="Update a single content attribute",
                path_parameters=["content_id", "attribute"],
                auth_required=True,
                allowed_groups=["Admin", "Publisher"]
            ),
            # Combined content search endpoint
            ApiRoute(
                method="POST",
                path="content/search",
                processor_name="content",
                action="search_content",
                description="Search content with flexible parameters and pagination (supports all query formats)",
                auth_required=True,
                allowed_groups=["Admin", "Publisher", "Consumer"]
            ),
            ApiRoute(
                method="POST",
                path="content/archive/{content_id}",
                processor_name="content",
                action="archive_content",
                description="Archive content",
                path_parameters=["content_id"],
                auth_required=True,
                allowed_groups=["Admin", "Publisher"]
            ),
            
            # License Management Routes - Restructured to avoid path parameter conflicts
            ApiRoute(
                method="POST",
                path="licenses/create",
                processor_name="license",
                action="create_license",
                description="Create a new license",
                auth_required=True,
                allowed_groups=["Admin", "Publisher", "Consumer"]
            ),
            ApiRoute(
                method="POST",
                path="licenses/get/{license_id}",
                processor_name="license",
                action="get_license",
                description="Get license by ID (POST)",
                path_parameters=["license_id"],
                auth_required=True,
                allowed_groups=["Admin", "Publisher", "Consumer"]
            ),
            ApiRoute(
                method="POST",
                path="licenses/search",
                processor_name="license",
                action="search_licenses",
                description="Search licenses with flexible parameters and pagination",
                auth_required=True,
                allowed_groups=["Admin", "Publisher", "Consumer"]
            ),
            ApiRoute(
                method="POST",
                path="licenses/revoke/{license_id}",
                processor_name="license",
                action="revoke_license",
                description="Revoke a license",
                path_parameters=["license_id"],
                auth_required=True,
                allowed_groups=["Admin", "Publisher", "Consumer"]
            ),
            
            # Analytics Routes
            ApiRoute(
                method="POST",
                path="analytics/access",
                processor_name="analytics",
                action="log_content_access",
                description="Log content access",
                auth_required=True,
                allowed_groups=["Admin", "Publisher", "Consumer"]
            ),
            ApiRoute(
                method="POST",
                path="analytics/reports/content/{content_id}",
                processor_name="analytics",
                action="get_usage_report_by_content",
                description="Get usage report by content (POST)",
                path_parameters=["content_id"],
                auth_required=True,
                allowed_groups=["Admin", "Publisher"]
            ),
            ApiRoute(
                method="POST",
                path="analytics/reports/consumer/{consumer_id}",
                processor_name="analytics",
                action="get_usage_report_by_consumer",
                description="Get usage report by consumer (POST)",
                path_parameters=["consumer_id"],
                auth_required=True,
                allowed_groups=["Admin", "Consumer"]
            ),
            
            # Google Books API Routes
            ApiRoute(
                method="POST",
                path="books/details/{isbn}",
                processor_name="google_books",
                action="get_book_details",
                description="Get complete book details by ISBN (POST)",
                path_parameters=["isbn"],
                auth_required=True,
                allowed_groups=["Admin", "Publisher"]
            ),
            ApiRoute(
                method="POST",
                path="books/filtered/{isbn}",
                processor_name="google_books",
                action="get_book_details_filtered",
                description="Get filtered book details by ISBN (POST)",
                path_parameters=["isbn"],
                auth_required=True,
                allowed_groups=["Admin", "Publisher"]
            ),
            ApiRoute(
                method="POST",
                path="books/search/author/{author_name}",
                processor_name="google_books",
                action="get_books_by_author",
                description="Get all books by a specific author (POST)",
                path_parameters=["author_name"],
                auth_required=True,
                allowed_groups=["Admin", "Publisher", "Consumer"]
            ),
            ApiRoute(
                method="POST",
                path="books/filtered/author/{author_name}",
                processor_name="google_books",
                action="get_books_by_author_filtered",
                description="Get filtered book details for all books by a specific author (POST)",
                path_parameters=["author_name"],
                auth_required=True,
                allowed_groups=["Admin", "Publisher", "Consumer"]
            ),
            
            # S3 Upload Routes
            ApiRoute(
                method="POST",
                path="uploads/url",
                processor_name="s3_upload",
                action="generate_presigned_upload_url",
                description="Generate a presigned URL for direct file upload to S3",
                auth_required=True,
                allowed_groups=["Admin", "Publisher"]
            ),
            ApiRoute(
                method="POST",
                path="uploads/download/{key}",
                processor_name="s3_upload",
                action="generate_presigned_download_url",
                description="Generate a presigned URL for file download from S3 (POST)",
                path_parameters=["key"],
                auth_required=True,
                allowed_groups=["Admin", "Publisher"]
            ),
            
            # S3 Multipart Upload Routes
            ApiRoute(
                method="POST",
                path="uploads/multipart/init",
                processor_name="s3_upload",
                action="initiate_multipart_upload",
                description="Initiate a multipart upload process",
                auth_required=True,
                allowed_groups=["Admin", "Publisher"]
            ),
            ApiRoute(
                method="POST",
                path="uploads/multipart/part-url",
                processor_name="s3_upload",
                action="generate_presigned_part_upload_url",
                description="Generate a presigned URL for uploading a specific part",
                auth_required=True,
                allowed_groups=["Admin", "Publisher"]
            ),
            ApiRoute(
                method="POST",
                path="uploads/multipart/complete",
                processor_name="s3_upload",
                action="complete_multipart_upload",
                description="Complete a multipart upload after all parts have been uploaded",
                auth_required=True,
                allowed_groups=["Admin", "Publisher"]
            ),
            ApiRoute(
                method="DELETE",
                path="uploads/multipart/abort",
                processor_name="s3_upload",
                action="abort_multipart_upload",
                description="Abort a multipart upload and remove any uploaded parts",
                auth_required=True,
                allowed_groups=["Admin", "Publisher"]
            ),
            ApiRoute(
                method="POST",
                path="uploads/multipart/parts/list",
                processor_name="s3_upload",
                action="list_parts",
                description="List all parts that have been uploaded for a specific multipart upload (POST)",
                auth_required=True,
                allowed_groups=["Admin", "Publisher"]
            ),
        ]
    
    @staticmethod
    def get_routes_by_processor(processor_name: str) -> List[ApiRoute]:
        """Get all routes for a specific processor"""
        return [route for route in KnowlioApiRoutes.get_all_routes() 
                if route.processor_name == processor_name]
    
    @staticmethod
    def get_route_by_method_and_path(method: str, path: str) -> Optional[ApiRoute]:
        """Get a specific route by HTTP method and path"""
        for route in KnowlioApiRoutes.get_all_routes():
            if route.method == method and route.path == path:
                return route
        return None
    
    @staticmethod
    def get_routes_by_group(group_name: str) -> List[ApiRoute]:
        """Get all routes that are accessible by a specific Cognito group"""
        all_routes = KnowlioApiRoutes.get_all_routes()
        accessible_routes = []
        
        # Map group names to processor access
        group_access = {
            "Admin": ["user", "content", "license", "analytics", "google_books", "s3_upload"],  # Admin can access everything
            "Publisher": ["content", "license", "analytics", "google_books", "s3_upload"]  # Publishers can access content, license, analytics, books, uploads
            # "Consumer": ["license", "google_books"]  # Consumers can access licenses, books, uploads
        }
        
        # Admin-only routes by path pattern
        admin_only_paths = [
            "admin/users/{user_id}",
            "admin/users"
        ]
        
        # Routes that are always public
        public_paths = [
            "register/users"
        ]
        
        for route in all_routes:
            # Public routes are accessible to all
            if any(public_path in route.path for public_path in public_paths):
                accessible_routes.append(route)
                continue
            
            # Admin-only routes
            if any(admin_path in route.path for admin_path in admin_only_paths):
                if group_name == "Admin":
                    accessible_routes.append(route)
                continue
            
            # Check if the group can access this processor's routes
            if group_name in group_access and route.processor_name in group_access[group_name]:
                accessible_routes.append(route)
        
        return accessible_routes
