# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# WARNING: AUTO-GENERATED FILE - DO NOT EDIT DIRECTLY
# 
# This file is automatically generated from infrastructure/config/api_routes.py
# by the sync_api_routes.py script.
# 
# To make changes, edit the source file and run sync_api_routes.py.
# Last synchronized: 2025-06-10 08:36:14
# 
# NOTE: This file was manually edited on 2025-06-11 to:
# 1. Remove the query_by_attribute route (GET content/query/{attribute}/{value})
#    as this functionality has been deprecated.
# 2. Remove list_content_by_publisher and list_content_by_publisher_and_type routes
#    as these have been consolidated into the search_content route.
# 3. Convert all GET routes to POST routes to prevent exposing parameters
#    in URLs and to ensure proper parameter type handling.
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

"""
API Gateway route configuration for Knowlio REST API.
Defines all processor actions as REST API endpoints with their HTTP methods and paths.
"""

from typing import List, Dict, Optional
from dataclasses import dataclass


@dataclass
class ApiRoute:
    """Configuration for a single API route"""
    method: str
    path: str
    processor_name: str
    action: str
    description: str
    path_parameters: Optional[List[str]] = None
    query_parameters: Optional[List[str]] = None


class KnowlioApiRoutes:
    """Central configuration for all Knowlio API routes"""
    
    @staticmethod
    def get_all_routes() -> List[ApiRoute]:
        """Return all API routes for the Knowlio system"""
        return [
            # User Management Routes
            ApiRoute(
                method="POST",
                path="users/register",
                processor_name="user",
                action="register_user",
                description="Register a new user",
            ),
            ApiRoute(
                method="POST",
                path="users/{user_id}",
                processor_name="user",
                action="get_user_profile",
                description="Get user profile by ID (POST)",
                path_parameters=["user_id"]
            ),
            ApiRoute(
                method="PUT",
                path="users/{user_id}",
                processor_name="user",
                action="update_user_profile",
                description="Update user profile",
                path_parameters=["user_id"]
            ),
            ApiRoute(
                method="POST",
                path="users/list",
                processor_name="user",
                action="list_users_by_role",
                description="List users by role with pagination (POST)",
            ),
            ApiRoute(
                method="POST",
                path="users/search",
                processor_name="user",
                action="search_users",
                description="Search users with flexible criteria",
            ),
            ApiRoute(
                method="PATCH",
                path="users/{user_id}/admin",
                processor_name="user",
                action="admin_update_user",
                description="Admin-only generic field update",
                path_parameters=["user_id"]
            ),
            
            # Content Management Routes
            ApiRoute(
                method="POST",
                path="content/metadata",
                processor_name="content",
                action="upload_content_metadata",
                description="Upload content metadata",
            ),
            ApiRoute(
                method="POST",
                path="content/{content_id}/get",
                processor_name="content",
                action="get_content_details",
                description="Get content details by ID (POST)",
                path_parameters=["content_id"]
            ),
            ApiRoute(
                method="PUT",
                path="content/{content_id}",
                processor_name="content",
                action="update_content_metadata",
                description="Update content metadata",
                path_parameters=["content_id"]
            ),
            ApiRoute(
                method="PATCH",
                path="content/{content_id}/attribute/{attribute}",
                processor_name="content",
                action="update_content_attribute",
                description="Update a single content attribute",
                path_parameters=["content_id", "attribute"]
            ),
            # Combined content search endpoint
            ApiRoute(
                method="POST",
                path="content/search",
                processor_name="content",
                action="search_content",
                description="Search content with flexible parameters and pagination (supports all query formats)",
            ),
            ApiRoute(
                method="POST",
                path="content/{content_id}/archive",
                processor_name="content",
                action="archive_content",
                description="Archive content",
                path_parameters=["content_id"]
            ),
            
            # License Management Routes
            ApiRoute(
                method="POST",
                path="licenses",
                processor_name="license",
                action="create_license",
                description="Create a new license",
            ),
            ApiRoute(
                method="POST",
                path="licenses/{license_id}/get",
                processor_name="license",
                action="get_license",
                description="Get license by ID (POST)",
                path_parameters=["license_id"]
            ),
            ApiRoute(
                method="POST",
                path="licenses/list",
                processor_name="license",
                action="list_licenses_by_consumer",
                description="List licenses by consumer (POST)",
            ),
            ApiRoute(
                method="POST",
                path="licenses/content/{content_id}/list",
                processor_name="license",
                action="list_licenses_by_content",
                description="List licenses by content (POST)",
                path_parameters=["content_id"]
            ),
            ApiRoute(
                method="POST",
                path="licenses/{license_id}/revoke",
                processor_name="license",
                action="revoke_license",
                description="Revoke a license",
                path_parameters=["license_id"]
            ),
            
            # Analytics Routes
            ApiRoute(
                method="POST",
                path="analytics/access",
                processor_name="analytics",
                action="log_content_access",
                description="Log content access",
            ),
            ApiRoute(
                method="POST",
                path="analytics/content/{content_id}/report",
                processor_name="analytics",
                action="get_usage_report_by_content",
                description="Get usage report by content (POST)",
                path_parameters=["content_id"]
            ),
            ApiRoute(
                method="POST",
                path="analytics/consumer/{consumer_id}/report",
                processor_name="analytics",
                action="get_usage_report_by_consumer",
                description="Get usage report by consumer (POST)",
                path_parameters=["consumer_id"]
            ),
            
            # Google Books API Routes
            ApiRoute(
                method="POST",
                path="books/{isbn}/details",
                processor_name="google_books",
                action="get_book_details",
                description="Get complete book details by ISBN (POST)",
                path_parameters=["isbn"]
            ),
            ApiRoute(
                method="POST",
                path="books/{isbn}/filtered",
                processor_name="google_books",
                action="get_book_details_filtered",
                description="Get filtered book details by ISBN (POST)",
                path_parameters=["isbn"]
            ),
            ApiRoute(
                method="POST",
                path="books/author/{author_name}/search",
                processor_name="google_books",
                action="get_books_by_author",
                description="Get all books by a specific author (POST)",
                path_parameters=["author_name"]
            ),
            ApiRoute(
                method="POST",
                path="books/author/{author_name}/filtered",
                processor_name="google_books",
                action="get_books_by_author_filtered",
                description="Get filtered book details for all books by a specific author (POST)",
                path_parameters=["author_name"]
            ),
            
            # S3 Upload Routes
            ApiRoute(
                method="POST",
                path="uploads/url",
                processor_name="s3_upload",
                action="generate_presigned_upload_url",
                description="Generate a presigned URL for direct file upload to S3"
            ),
            ApiRoute(
                method="POST",
                path="uploads/download/{key}",
                processor_name="s3_upload",
                action="generate_presigned_download_url",
                description="Generate a presigned URL for file download from S3 (POST)",
                path_parameters=["key"]
            ),
            
            # S3 Multipart Upload Routes
            ApiRoute(
                method="POST",
                path="uploads/multipart/init",
                processor_name="s3_upload",
                action="initiate_multipart_upload",
                description="Initiate a multipart upload process"
            ),
            ApiRoute(
                method="POST",
                path="uploads/multipart/part-url",
                processor_name="s3_upload",
                action="generate_presigned_part_upload_url",
                description="Generate a presigned URL for uploading a specific part"
            ),
            ApiRoute(
                method="POST",
                path="uploads/multipart/complete",
                processor_name="s3_upload",
                action="complete_multipart_upload",
                description="Complete a multipart upload after all parts have been uploaded"
            ),
            ApiRoute(
                method="DELETE",
                path="uploads/multipart/abort",
                processor_name="s3_upload",
                action="abort_multipart_upload",
                description="Abort a multipart upload and remove any uploaded parts"
            ),
            ApiRoute(
                method="POST",
                path="uploads/multipart/parts/list",
                processor_name="s3_upload",
                action="list_parts",
                description="List all parts that have been uploaded for a specific multipart upload (POST)"
            ),
        ]
    
    @staticmethod
    def get_routes_by_processor(processor_name: str) -> List[ApiRoute]:
        """Get all routes for a specific processor"""
        return [route for route in KnowlioApiRoutes.get_all_routes() 
                if route.processor_name == processor_name]
    
    @staticmethod
    def get_route_by_method_and_path(method: str, path: str) -> Optional[ApiRoute]:
        """Get a specific route by HTTP method and path"""
        for route in KnowlioApiRoutes.get_all_routes():
            if route.method == method and route.path == path:
                return route
        return None
